// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8rHdewwbyALgYBMl0Ilxbea___RQ0fSY',
    appId: '1:923250040637:web:cc044a0243c26837afef54',
    messagingSenderId: '923250040637',
    projectId: 'productmanager-c654d',
    authDomain: 'productmanager-c654d.firebaseapp.com',
    storageBucket: 'productmanager-c654d.appspot.com',
    measurementId: 'G-525EF0P9EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxeFRtESV03zAXLTNsfBxCocCMXfIm094',
    appId: '1:923250040637:android:df71416ad845379fafef54',
    messagingSenderId: '923250040637',
    projectId: 'productmanager-c654d',
    storageBucket: 'productmanager-c654d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmhWXK1UfmIahXg6HFedWVyzE7ySc4hKk',
    appId: '1:923250040637:ios:7d07374cfd2fe8bbafef54',
    messagingSenderId: '923250040637',
    projectId: 'productmanager-c654d',
    storageBucket: 'productmanager-c654d.appspot.com',
    iosClientId:
        '923250040637-bm8rvdcbvi6sn8tlbsms1pjn9g7t19qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.productManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmhWXK1UfmIahXg6HFedWVyzE7ySc4hKk',
    appId: '1:923250040637:ios:7d07374cfd2fe8bbafef54',
    messagingSenderId: '923250040637',
    projectId: 'productmanager-c654d',
    storageBucket: 'productmanager-c654d.appspot.com',
    iosClientId:
        '923250040637-bm8rvdcbvi6sn8tlbsms1pjn9g7t19qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.productManager',
  );
}
